const mobileStrings: { [key: string]: any } = {
  "3d_secure_bullet_one": "The identification process varies from bank to bank",
  "3d_secure_bullet_three": "Please don’t close the following page, otherwise your transaction won't be finalized",
  "3d_secure_bullet_two": "Once the bank confirms your identity, we'll be able to complete your order",
  "3d_security_header_description": "To prevent the misuse of your card, you may be required to identify yourself with your bank",
  "3d_security_header_title": "Securing your payment",
  "3d_security_title": "Secure checkout",
  "Orders_paragraph": "View all your orders here, including earned and redeemed Rewards and Offers.",
  "abandon_cart_message": "Your unfinished order at {{venue_name}}  will be deleted",
  "abandon_cart_title": "Start a new order?",
  "abort": "Abort",
  "abort_registration_message": "We need your email to create your account",
  "abort_registration_title": "Abort registration?",
  "accessibility_header_error": "{{name}}, {{rule}}, error",
  "account": "Account",
  "account_created_no_referral_desc": "Now you are part of the loyalty program. Enjoy all the benefits.",
  "account_created_no_referral_title": "Account created",
  "account_updated": "Account updated",
  "accrual_max_points": "‼️ Maximum {{point_name}} reached. You won't get full amount of {{point_name}}.",
  "accrual_points": "Hooray 🎉  You'll get {{number_of_points}} {{point_name}}",
  "active_offer": "Active offer ready to be used",
  "active_reward": "Active reward ready to be used",
  "add": "Add",
  "add_birthday": "Add birthday",
  "add_building_number": "Add building number",
  "add_code_create_account": "Add code and Create account",
  "add_color": "Add color",
  "add_details": "Add details",
  "add_discount_card": "Add discount card",
  "add_email": "Add email",
  "add_first_name": "Add first name",
  "add_last_name": "Add last name",
  "add_new_address_button": "Add new address",
  "add_password": "Add password",
  "add_payment_method": "Add payment method",
  "add_place_number": "Add {{place}} number",
  "add_plate_number": "Add plate number",
  "add_vehicle_details": "Add your vehicle details",
  "add_your_vehicle": "Add your vehicle",
  "add_zip_code": "Add ZIP code",
  "address_confirmation_body": "Your pin doesn't match the written address. The order will be delivered to the pin location. If you're certain the address is correct you can confirm and continue.",
  "address_confirmation_title": "Confirm your address",
  "address_not_available_1": "Your current address was not available for selected restaurant so we switched to first nearest restaurant available",
  "address_not_available_2": "Your current address was not available for selected restaurant so we switched to list of nearest restaurants available",
  "all_venues_are_closed": "All venues are currently closed",
  "allergens": "Allergens",
  "already_have_offer_tooltip": "You already have an offer in the cart",
  "already_have_referral_dialogue_paragraph": "We've added it for you",
  "already_have_referral_dialogue_title": "Looks like you already have a referral offer!",
  "already_have_reward_tooltip": "You already have a reward in your cart",
  "already_left_feedback": "You already left feedback. We’re looking forward to your next order!",
  "apartment": "Apartment",
  "apartment_floor_input_placeholder": "{{apartment}} \/ {{floor}}",
  "apple_pay": "Apple Pay",
  "apple_pay_description": "We’ll ask you to log-in with Apple Pay when placing an order",
  "apple_pay_title": "Use Apple Pay",
  "apply": "Apply",
  "area_location_type_with_number": "{{area_location_type}} number",
  "asap": "ASAP",
  "asap_in_about": "ASAP (in about {{time}} min)",
  "auth_instruction": "Instructions to sign in or create an account are sent to {{email}} ",
  "back_to_discount": "Back to discount",
  "barcode_already_used_error": "Code already used",
  "barcode_not_valid_error": "Code is not valid or incorrect",
  "bill_cant_be_settled": "This bill can't be settled",
  "bill_cant_be_settled_info_message": "Please settle your bill with the waiter instead",
  "bill_in_process_dialog_message": "Someone else is already paying the bill. Try again shortly.",
  "bill_in_process_dialog_title": "Order is being paid",
  "bill_modified_dialog_message": "This bill changed and we need to refresh it",
  "bill_modified_dialog_title": "New bill details",
  "birthday": "Birthday",
  "birthday_input_note": "Note: Birthday can’t be changed later",
  "brand_and_model": "Brand and model",
  "bring_your_order": "We’ll bring your order right out",
  "building_number_placeholder": "Building Number \/ Name",
  "call": "Call",
  "cancel": "Cancel",
  "cancel_order": "Cancel order",
  "card_expired": "Card expired",
  "card_expired_empty_error": "Add date",
  "card_number": "Card Number",
  "cards_active_modal_description": "Rewards & Offers cannot be added while a discount card is active. Remove cards to add a reward or an offer.",
  "cards_active_modal_title": "Discount cards are active",
  "cash_payment_method": "Cash",
  "center_barcode_info": "Center the code found on your receipt",
  "change": "Change",
  "change_address": "Change address",
  "change_amount_creditbalance_error": "Amount can’t be higher than {{credit_balance}}",
  "change_amount_info": "The credit amount can't be higher than your total order ({{total_order_amount}}). You have {{credit_available}}  available",
  "change_amount_orderamount_error": "Amount can’t be higher than {{order_amount}}",
  "change_password": "Change password",
  "change_to_order_type": "Change to {{order_type}}?",
  "check_your_inbox": "Check your inbox",
  "check_your_spam_folder": "Didn't get email? Check your spam folder.",
  "choose_combo": "Choose combo",
  "choose_your_bank": "Choose your bank",
  "city_placeholder": "City",
  "clear": "Clear",
  "clear_all": "Clear all",
  "close": "Close",
  "close_announcement": "Close Announcement",
  "closed": "Closed",
  "code": "Code {{code}} ",
  "code_copied": "Code copied",
  "collect_instructions_kiosk": "Scan this code at the kiosk, or enter the card number manually",
  "collect_instructions_pos": "Put this code under the cash register's scanner",
  "collect_instructions_pos_kiosk": "Put this code under the scanner of the kiosk or cash register. Or, you can enter the card number manually.",
  "collect_instructions_pos_kiosk_new": "Scan this code at the kiosk or cash register. Or, you can enter the card number manually.",
  "collect_instructions_pos_new": "Scan this code at the cash register",
  "collect_points": "Collect {{points}}",
  "collect_points_at_cash_register": "Collect {{points}} at cash register",
  "collect_points_instructions_description": "Select \"Collect {{points}}\" on kiosk checkout. Bring your phone facing the barcode scanner to collect {{points}} from your kiosk order.",
  "collect_points_on_kiosk": "Collect {{points}} on kiosk",
  "collect_points_on_kiosk_or_cash_register": "Collect {{points}} on kiosk or cash register",
  "collect_points_title": "How do you want to collect points?",
  "collect_these_yourself": "Collect these yourself",
  "comment_hint": "For example \"No olives please\"",
  "condition_certain_amount_name": "Spend {{number}}",
  "confirm": "Confirm",
  "confirm_location": "Confirm location",
  "congratulations": "Congratulations!",
  "connect": "CONNECT",
  "contact": "Contact {{brand_name}} ",
  "contact_url": "\"\"",
  "continue": "Continue",
  "continue_with_apple": "Continue with Apple",
  "continue_with_email": "Continue with email",
  "continue_with_facebook": "Continue with Facebook",
  "could_not_add_payment_method_dialog_message": "Double-check and try again",
  "could_not_add_payment_method_dialog_title": "Couldn't add payment method",
  "coupon": "Coupon",
  "coupon_disclaimer_text": "*Only in participating restaurants. Recommended retail price.",
  "coupon_will_disappear_description": "Coupon will disappear when time runs out, or if you close this screen",
  "coupons": "Coupons",
  "coupons_in_article_title": "Coupons in this article",
  "courier_collected_delivery": "Courier just collected your order. Enjoy!",
  "create_account": "Create account",
  "create_account_sign_in": "Create account • Sign in",
  "create_account_to_proceed": "Create account or sign in to proceed",
  "create_new_account": "Create new account",
  "create_password": "Finally, a memorable password",
  "credit_balance": "Credit balance",
  "credit_card": "Credit card",
  "credit_card_cvv_hint": "CVV",
  "credit_card_expiration_date": "Expiry date",
  "credit_card_expiration_hint": "MM \/ YY",
  "credit_card_non_storable_body": "Please insert your credit card information at each checkout",
  "credit_card_non_storable_label": "Non-storable card",
  "credit_card_non_storable_title": "We are not allowed to store this credit card information",
  "credit_card_security_code": "Security code",
  "credits_offers": "Credits & Offers",
  "curbside_description": "Park and we'll bring it out to you",
  "curbside_order_ready_description": "We'll be right out with your order. Enjoy!",
  "current_location": "Current location",
  "current_password": "Current password {{required}} ",
  "currently_closed": "Closed right now. Can't make an order.",
  "customize": "Customize",
  "cycling": "Cycling",
  "date_at_time": "{{date}} at {{time}}",
  "delete": "Delete ",
  "delete_account": "Delete account",
  "delete_account_body": "If you delete your account",
  "delete_account_bullet_1": "You will no longer be able to log in with your account",
  "delete_account_bullet_2": "You will no longer be able to see receipts of all of your past orders",
  "delete_account_bullet_3": "You will no longer be able to order delicious meals from our restaurants",
  "delete_account_bullet_4": "You will no longer be able to access our latest offers",
  "delete_account_bullet_loyalty": "You will lose your {{number}} {{loyalty_points_name}}",
  "delete_account_confirmation": "Your account has been deleted",
  "delete_account_dialog_body": "Your account will be permanently deleted",
  "delete_account_dialog_title": "Are you sure you want to delete your account?",
  "delete_account_note": "{{note}} It can take up to 6 months for your data to be completely removed from our systems. Please review our {{privacy_policy}} for further information.",
  "delete_account_time": "This can take up to 1 minute to complete",
  "delete_card": "Delete card",
  "delete_discount_card": "Delete this discount card?",
  "delete_payment_method_dialog_title": "Delete this payment method?",
  "deliver_to": "Deliver to",
  "delivery": "Delivery",
  "delivery_address": "Delivery address",
  "delivery_card_description": "Order is delivered to you",
  "delivery_choose_on_map": "Choose manually on the map",
  "delivery_closed": "Delivery closed",
  "delivery_closed_message": "{{delivery_closed}}. {{too_late_to_order}}",
  "delivery_fee": "Delivery fee",
  "delivery_fee_body": "Your delivery fee is affected by rush hours. Please review it again before placing the order.",
  "delivery_fee_title": "Delivery fee changed",
  "delivery_for_around_time_on_the_way": "Delivery for around {{time}} is on the way ",
  "delivery_for_time_on_the_way": "Delivery for {{time}} is on the way",
  "delivery_order_placed_status_description": "You'll get a notification when it's on the way",
  "delivery_placed_for": "Delivery placed for {{time}} ",
  "delivery_placed_for_around": "Delivery placed for around {{time}} ",
  "delivery_tab": "{{delivery}}",
  "delivery_time_minutes": "{{time}} min",
  "delivery_venue_closed_message": "Restaurant delivering to your address is currently closed",
  "delivery_venue_closed_title": "Restaurant closed",
  "demographic_data_company_name": "Company name",
  "demographic_data_company_name_empty": "Add company name",
  "demographic_data_identification_number": "Identification number",
  "demographic_data_identification_number_empty": "Add identification number",
  "demographic_heading_description": "We'll use this info to personalize offers, rewards, and promotions.",
  "demographic_heading_title": "We'd like to get to know you better",
  "deprecate_key_for_deletion": "Test message for to be deleted",
  "dialog_add_items_order_desc": "To use your available credits, you must add items to your order",
  "dialog_add_items_order_title": "Add items to your order",
  "dialog_cancel_order_failed_body": "For any additional assistance, please call the restaurant",
  "dialog_cancel_order_failed_title": "There was an interruption and we couldn't cancel your order",
  "dialog_change_address_body": "A different restaurant delivers to your new address, so your unfinished order will be deleted",
  "dialog_change_address_title": "Change address?",
  "dialog_coming_soon_desc": "{{restaurant_name}} doesn't accept credits yet. Please try again later.",
  "dialog_coming_soon_title": "Coming soon!",
  "dialog_delivery_promise_drivers_unavailable_description": "Please try again later",
  "dialog_delivery_promise_drivers_unavailable_title": "We don't have any drivers available right now",
  "dialog_delivery_promise_fee_changed_description": "Please check the new delivery fee before confirming the order",
  "dialog_delivery_promise_fee_changed_title": "Delivery fee changed",
  "dialog_delivery_promise_fee_time_changed_description": "Please check the new delivery fee and time before confirming the order",
  "dialog_delivery_promise_fee_time_changed_title": "Delivery details changed",
  "dialog_no_credit_available_desc": "You don't have enough credits available. Collect more points to increase your credit balance.",
  "dialog_no_credit_available_title": "No credits available",
  "dialog_offer_not_available_news_heading": "Available soon!",
  "dialog_offer_not_available_news_paragraph": "This offer will become available on {{date}}",
  "dialog_offer_remove_item_body": "Removing this item will reduce your cart total below the amount needed to unlock the offer",
  "dialog_remove_item_body": "Removing this item will reduce the total amount in your cart needed to unlock the offer",
  "dialog_remove_item_title": "Remove item?",
  "dialog_reset_password_body": "We'll send instructions on how to reset your password to {{email}}",
  "dialog_reset_password_title": "Reset password?",
  "dialog_reward_remove_item_body": "Removing this item will reduce your cart total below the amount needed to unlock the reward",
  "dine_in": "Dine-in",
  "dine_in_fs": "Dine-in",
  "dine_in_fs_info": "Order is served in restaurant",
  "dine_in_qs": "Dine-in",
  "dine_in_qs_info": "Order is served in restaurant",
  "directions": "Directions",
  "discard_order_modifications_dialog_cta": "Discard",
  "discard_order_modifications_dialog_description": "Modifications you made to this order will not be saved",
  "discard_order_modifications_dialog_title": "Discard order modifications?",
  "discount": "Discount",
  "discount_already_added_dialog_message": "Sorry, you can add only 1 discount to your order",
  "discount_already_added_dialog_title": "You already have a discount",
  "discount_card_note": "Note: You can use one type of discount card at a time",
  "discount_cards": "Discount cards",
  "discount_cards_description": "Discount will be applied to whole order",
  "discount_cards_description_memc_false": "Discount will be applied to the amount of {{memc}}",
  "discount_cards_description_memc_true": "Discount will be applied to the amount of {{memc}} per added card",
  "discount_condition_instruction": "Meet conditions to unlock discount",
  "discount_expires": "Expires {{date}}",
  "discount_expires_at": "Expires {{date}} at {{time}}",
  "discount_not_available_for_address_message": "Restaurant delivering to your address doesn't offer this discount",
  "discount_not_available_for_address_title": "Discount is not available for your address",
  "discount_will_expire_message": "You'll have 5 minutes to use it",
  "discounts_not_available_dialog_description": "Looks like some offers and rewards are not available at this time",
  "done": "Done",
  "driving": "Driving",
  "earn_points": "Earn {{points}},",
  "easiest_way_to_order": "The easiest way to order",
  "edit": "Edit",
  "edit_email": "Edit email address",
  "edit_phone": "Edit phone number",
  "email": "Email {{required}}",
  "email_changed": "Email changed",
  "email_check_registered_message": "This email is already in use",
  "empty_card_number_error": "Add card number",
  "empty_cvv_error": "Add CVV",
  "enjoy": "Enjoy!",
  "enjoy_loyalty_benefits_title": "Do you want to enjoy all loyalty benefits?",
  "enter_cash_amount": "Enter cash amount",
  "enter_cash_amount_description": "Please enter the amount of cash you have so the courier can prepare change for you",
  "enter_code": "Enter Code",
  "enter_code_manually": "Enter code manually",
  "enter_code_on_kiosk": "Alternatively, you can enter this code on kiosk",
  "enter_code_on_kiosk_or_cash_register": "Alternatively, you can enter this code on kiosk or at cash register",
  "enter_promo_code": "Enter promo code",
  "enter_receipt_code_manually": "Enter the receipt code number manually",
  "enter_redemption_code_manually": "Alternatively, you can enter {{redemption_code}} manually",
  "enter_the_code": "Enter the code",
  "error_brand_and_model": "Add brand and model",
  "error_password_validation": "Minimum 7 characters including at least 1 number",
  "expect_notification": "You'll get a notification when it's ready",
  "expired": "Expired",
  "expires_on_date": "Expires on {{expirarion_date}}",
  "expiry_date": "Expiry date",
  "facebook_failed_dialog_message": "We need Facebook access to continue",
  "facebook_failed_dialog_title": "That didn't work",
  "faq": "FAQ",
  "fee_for_orders_below": "Fee for orders below {{minimum_amount}} ",
  "field_required": "This field is required",
  "filter_by": "Filter by",
  "filters": "Filters",
  "finally_whatIs_your_name": "Finally, what's your name?",
  "find_barcode_desc": "You can find the barcode number on your receipt",
  "find_qrcode_desc": "You can find the QR code number on your receipt",
  "first_name": "First name {{required}} ",
  "first_order_condition": "On 1st order",
  "floor": "Floor",
  "follow": "Follow {{brand_name}}",
  "follow_your_order": "Follow your order",
  "foodspot": "Foodspot",
  "foodspot_address": "Foodspot address",
  "foodspot_card_description": "Order is delivered to a station",
  "foodspot_closed": "Foodspot closed",
  "foodspot_closed_message": "{{foodspot_closed}}. {{too_late_to_order}}",
  "foodspot_code_error": "Wrong code",
  "foodspot_deadline_time": "Orders are accepted until {{time}}",
  "foodspot_directory_description": "Get the code from your organization",
  "foodspot_directory_section_title": "Previously used",
  "foodspot_directory_store_finder": "This restaurant is only available through Foodspot ordering",
  "foodspot_discount_description": "{{number}}% off your order",
  "foodspot_for_time_on_the_way": "Foodspot for {{time}} is on the way ",
  "foodspot_marketing_description": "Foodspot is a convenient way of ordering on site food. Offer companies and communities a platform to allow employees or group of people to order delivery to a station.",
  "foodspot_marketing_link": "Find out more",
  "foodspot_marketing_title": "Introducing Foodspot",
  "foodspot_placed_for": "Foodspot placed for {{time}} ",
  "foodspot_subsidy": "Foodspot Subsidy",
  "foodspot_subsidy_amount": "Foodspot Subsidy ({{subsidy_amount}})",
  "forgot_password_question": "Forgot password?",
  "free_delivery": "Free delivery",
  "freshest_meal": "Get the freshest meal possible",
  "friday": "Friday",
  "gcash": "Gcash",
  "gcash_description": "We'll ask you to log-in with GCash when placing an order",
  "gcash_title": "Use GCash",
  "gdpr_addinfo_one": "\"\"",
  "gdpr_addinfo_two": "\"\"",
  "gdpr_description": "We'll use your data to tailor special deals and promotions just for you. We're not selling your data.",
  "gdpr_opt_in_switch_description": "I'd like to receive special deals and promotions via push notifications and emails. Opt-out any time in notification settings.",
  "gdpr_terms_of_service": "I agree to the {{terms_of_service}}.",
  "gdpr_title": "We deeply care about your privacy",
  "generic_error_message": "There was an interruption and we couldn't do what you wanted us to do",
  "generic_error_title": "We ran into a problem :(",
  "give_instructions": "Give instructions",
  "gmail": "Gmail",
  "go_back": "Go back",
  "go_to_offers": "Go to Offers",
  "go_to_restaurant": "Go to restaurant and collect it",
  "go_to_settings": "Go to settings",
  "good_afternoon": "Good afternoon",
  "good_evening": "Good evening",
  "good_morning": "Good morning",
  "google_maps": "Google Maps",
  "google_pay": "Google Pay",
  "google_pay_description": "We’ll ask you to log-in with Google Pay when placing an order",
  "google_pay_title": "Use Google Pay",
  "got_it_button": "Got it",
  "got_refrerral_dilogue_paragraph": "Go to Offers to add it to your cart",
  "got_refrerral_dilogue_title": "Woohoo! You got a referral offer!",
  "head_to_cash_register_message": "Please head to the cash register to pay your order. You’ll then get a notification when it’s ready.",
  "hello": "Hello{{customer_name}},",
  "hi": "Hi {{customer_name}} ",
  "hide_password": "Hide password",
  "hint_brand_model": "e.g. Chevrolet Onix",
  "home_in_tab_bar": "Home",
  "hooray": "Woohoo!",
  "how_it_works": "How it works",
  "i_agree": "I agree to the Terms of Service",
  "iam_here_tapped": "We'll be right out with your order",
  "ideal_description": "We’ll ask you to choose your bank and log-in when placing an order",
  "im_here_button": "I'm here",
  "imprint": "Imprint",
  "in_about": "in about {{number_of_minutes}} min",
  "in_about_with_order_type": "{{order_type}} in about {{number_of_minutes}} min",
  "in_store": "In Store",
  "in_store_desc": "Scan your code at the kiosk or show at the cash register",
  "instructions_input_placeholder": "Instructions for courier",
  "invalid_phone_number": "Invalid phone number",
  "invite_history": "Invite history",
  "invite_history_empty": "Your invite history will show up here when your friends use your referral code to place their first order",
  "it_is_closing_time": "It's closing time",
  "it_is_closing_time_message": "It's closing time. Too late to order now.",
  "it_is_to_late_to_order_now": "Sorry, it's too late to order now",
  "item_food_type_calories_and_allergens_description": "Food type, calories and allergens vary based on modifications made to item. 2000 calories a day is used for general nutrition advice, but calorie needs vary. Additional information available upon request.",
  "item_not_available": "This item is not available",
  "items_removed_from_order": "Some items are not available. They are removed from your order.",
  "join_now": "Join now!",
  "join_start_earning": "Join and start earning",
  "just_a_moment": "Just a moment...",
  "kcal": "kcal",
  "keep_app_running": "Please keep the app running in the background so we’re able to detect when you are nearby",
  "kiosk_scan_instructions": "Kiosk scan instructions",
  "kiosk_scan_instructions_description": "Select \"Add discount\" on kiosk. Bring your phone facing the barcode scanner to add the discount to your kiosk order.",
  "kiosk_scan_instructions_description_new": "Select \"Use offer or reward\" on a kiosk. Scan the code displayed on your phone on the kiosk to add it to your order.",
  "last_name": "Last name {{required}}",
  "lastly_referral_code_desc": "If someone invited you to join, add the referral code they gave you to unlock a special offer. Otherwise, you can skip this step and create an account without it.",
  "lastly_referral_code_title": "Lastly, add a referral code",
  "legal": "LEGAL",
  "lets_start": "Let's start",
  "location": "Location",
  "logged_out_message": "To verify your account, sign in again",
  "logged_out_title": "Making sure it’s you",
  "logout_dialog_message": "Are you sure you want to sign out?",
  "logout_dialog_title": "We'll miss you",
  "low_cash_amount": "Cash amount can't be lower than bill",
  "loyalty_currency_active_desc": "Offer will disappear when time runs out. The credit selected will return to your balance if you don’t use it until the countdown ends.",
  "loyalty_currency_camera_access_desc": "This will enable the camera access which is needed to scan bardcode to collect your points",
  "loyalty_currency_camera_access_title": "{{app_name}} Would Like to Access the Camera",
  "loyalty_currency_desc": "You earn {{reward_currency}}  credits for every{{total_points}}  {{points}}",
  "loyalty_currency_mobile_app": "To use credits on your mobile app, you must have items in your order",
  "loyalty_currency_total_points_reach_snackbar": "Woohoo! You just reached {{total_points}}  points. {{reward_currency}}  was added to your credit balance.",
  "loyalty_paragraph_for_guests": "Your rewards will show up here. Sign in or create account to start earning rewards.",
  "loyalty_points_to_reward_desc": "You need {{missing_points}} more {{points_name}} to earn a {{offer_name}}",
  "loyalty_pointsunlock_active_offer": "This offer will disappear when the time runs out",
  "loyalty_pointsunlock_active_reward": "This reward will disappear when the time runs out",
  "loyalty_program_desc": "\"\"",
  "loyalty_program_desc_heading1": "\"\"",
  "loyalty_program_desc_heading2": "\"\"",
  "loyalty_program_desc_heading3": "\"\"",
  "loyalty_program_desc_paragraph1": "\"\"",
  "loyalty_program_desc_paragraph2": "\"\"",
  "loyalty_program_desc_paragraph3": "\"\"",
  "loyalty_program_title": "Your rewards",
  "mail_default": "Mail (default)",
  "make_it_a_combo": "Make it a combo?",
  "manage": "MANAGE",
  "map_default_info_paragraph": "Move the map to select your exact location. We’ll deliver where the pin is placed.",
  "map_preview_info_paragraph": "Orders are delivered based on the location shown on the map.",
  "map_zoom_in_info_paragraph": "Please zoom in to find your exact location",
  "maps": "Maps",
  "max_cards_reached": "Maximum number of cards reached. Remove a card to add a new one.",
  "max_cash_amount_error": "Input is higher than maximum cash amount",
  "max_points_reached": "You've reached the maximum number of {{points}}. You can't get any more.",
  "max_points_will_be_reached": "You're going to reach the maximum number of {{points}}. You won't get the full amount.",
  "maximum_characters": "Maximum {{number_of_characters}} characters",
  "maximum_points_reached": "You've reached the maximum number of {{points}}. Now it's time to start using them so you can collect even more.",
  "menu_not_available_dialog_description": "Looks like some items or customisations are not available at this time",
  "mercado_pago_description": "We’ll ask you to log-in with Mercado Pago when placing an order",
  "minimum_order_amount_message": "The minimum order size is {{minimum_amount}}. You can still place the order, but unfortunately we have to charge you the difference.",
  "mobile_ordering_not_available": "Not available for mobile ordering",
  "monday": "Monday",
  "more_filters": "More filters",
  "multiple_active_orders": "{{number}} active orders ",
  "must_add_items_kiosk_order": "You must have items added to your kiosk order to use your credits",
  "my_orders": "My orders",
  "nearest": "Nearest",
  "new_order": "New Order",
  "new_password": "New password {{required}}",
  "news": "News",
  "next": "Next",
  "no_coupons_info_message": "Your coupons will show up here. We'll inform you when new coupons are available.",
  "no_delivery_venues_message": "Oh snap! We can't deliver to this address. Stay tuned as we constantly add new delivery locations.",
  "no_details": "No details",
  "no_expiry_date": "No expiry date",
  "no_internet_connection": "No internet connection",
  "no_internet_message": "You need to be online to see venues and to order something delicious from them",
  "no_lines_no_waiting": "No lines. No waiting.",
  "no_payment_methods_message": "Payment methods will show up here. Go ahead and add one.",
  "no_promotions_info_message": "Your promotions will show up here. To get a promotion enter a promo code.",
  "no_receipts": "Your receipts will show up here. Go ahead and order something delicious.",
  "no_restaurants_message": "Oh snap! We can't find any location near you. Stay tuned as we constantly cover new locations.",
  "no_results": "No results",
  "no_results_for_filters": "There are no offers for the selected filters",
  "no_rewards_available": "Your rewards will show up here, once they are available",
  "non_stop_working_hours": "open 24h",
  "not_available": "Not available",
  "not_available_for_order_type": "Some items are not available for {{order_type}}. They will be removed from your order.",
  "not_eligible_offer_dialogue_heading": "You are not eligible for this offer",
  "not_eligible_offer_dialogue_paragraph": "This offer can be only used with your first order",
  "not_eligible_referral_dialogue_heading": "You are not eligible for this referral",
  "not_eligible_referral_dialogue_paragraph": "This referral can be only used with your first order",
  "not_use_smart_orders_recommendation": "We recommend you not use Smart orders, since we will only start preparing your order after you tap on “I’m on my way”",
  "note": "Note:",
  "nothing_to_settle": "Nothing to settle",
  "nothing_to_settle_info_message": "When you order with the waiter it will show up here. Then you can settle your bill with the app.",
  "notification_message": "Turn on notifications and get updated when your order is ready. Otherwise, you might miss it.",
  "notification_promo_email_description": "Get notified about special offers, rewards and promotions",
  "notification_promo_email_title": "Promo emails",
  "notification_promo_push_description": "Get notified about special offers, rewards and promotions",
  "notification_promo_push_title": "Promo push notifications",
  "notification_settings": "Notification settings",
  "notifications": "Notifications",
  "notifications_off": "{{notifications}} {{off}}  ",
  "notifications_on": "{{notifications}} {{on}} ",
  "number_of_coupons_left": "{{number}} left",
  "number_of_points": "{{number}} {{points}} ",
  "off": "OFF",
  "offer": "Offer",
  "offer_already_added_dialog_title": "You already have an offer",
  "offer_condition_instruction": "Meet conditions to unlock the offer",
  "offer_empty_desc": "Your offers will show up here once they are available. If you have a promo code, enter it to enjoy its benefits.",
  "offer_emptystate_info": "Your offers will show up here once they are available. If you have a promo code, enter it to enjoy its benefits.",
  "offer_expires_days": "Expires in {{number}} day(s)",
  "offer_expires_days_time": "Expires in {{number}} day(s) at {{time}}",
  "offer_not_available": "You got the offer but it’s not available here",
  "offer_not_available_order_types": "This offer is only available for {{order_types}}",
  "offer_not_available_ordering_flow": "This offer is only available from the restaurant menu",
  "offer_not_available_restaurant": "This offer is only available in participating restaurants",
  "offer_or_reward_already_added_dialog_message": "Sorry, you can add only one offer or reward to your order",
  "offer_unavailable_item_snackbar": "This offer isn’t available for the selected order type",
  "offer_will_disappear_description": "Offer will disappear when time runs out, or if you close this screen",
  "offers": "Offers",
  "offers_and_credits": "Offers & Credits",
  "offers_and_rewards": "Offers & Rewards",
  "offers_bottom_tab": "Offers",
  "offers_empty_state_desc": "Your offers will show up here. We'll inform you when new ones are available.",
  "offers_home_heading": "Offers",
  "offers_in_article_title": "Offers in this article",
  "ok": "OK",
  "on": "ON",
  "on_my_way_button": "I’m on my way",
  "on_my_way_description": "Tap “I’m on my way” below when you start your journey to the restaurant",
  "onboarding_privacy_text": "By proceeding you confirm that you have read our {{privacy_policy}} ",
  "open_email_app": "Open email app",
  "opening_hours": "Opening hours",
  "opens_at": "Opens at {{time}}",
  "opt_out": "Opt out",
  "optout_dialog_paragraph": "If you decide to no longer be a part of loyalty program you must delete your account.",
  "optout_dialog_title": "To opt out you must delete \u2028your account",
  "order": "Order",
  "order_at_nearby_restaurants": "Order at nearby restaurants.",
  "order_cancelled": "Order cancelled",
  "order_fail_notification_message": "Your order at {{venue}}  has not been created due to an error. Please check your payment method or try again later. If you have been charged, a refund will be issued to you within a few days",
  "order_for": "ORDER FOR",
  "order_has_changed_dialog_description": "Some items, prices or offers may have changed since your last order",
  "order_has_changed_dialog_title": "Please check carefully before placing the order",
  "order_in_advance": "{{opens_at}} • Order in advance",
  "order_is_on_the_way": "Your order is on the way. Enjoy!",
  "order_is_packed_for_outside": "Order is packed for outside",
  "order_is_served_in_restaurant": "Order is served in restaurant",
  "order_number": "Order #{{order_code}}",
  "order_number_cash": "Head to a cashier and pay using your order number. You'll then get a notification when your order is ready.",
  "order_number_code": "{{order_number}} ",
  "order_number_empty": "Your order number has not yet been assigned. We'll send you a notification when it is available.",
  "order_number_filled": "Your order number",
  "order_number_notification_title": "{{number}} is your order number",
  "order_number_ond": "Your order number will appear on the restaurant's orders screen when it's ready",
  "order_number_ond_cash": "Head to a cashier and pay using your order number. Your order number will appear on the restaurant's orders screen when it's ready.",
  "order_number_placeholder": "_ _ _",
  "order_paid": "Order paid",
  "order_percentage_discount": "Discount ({{value}}%)",
  "order_placed": "Order placed",
  "order_placed_for_around": "Order placed for around {{time}} ",
  "order_placed_for_time": "Order placed for {{time}} ",
  "order_ready": "Order ready!",
  "order_refunded": "Order refunded",
  "order_time_changed": "Order time changed",
  "order_time_changed_description": "Selected time isn’t available. It’s changed to first available time slot.",
  "order_time_changed_message": "Your selected time wasn't available. We changed it to the first available time.",
  "order_time_changed_title": "Order time changed",
  "order_type_curbside": "Curbside",
  "order_type_for": "{{order_type}} for {{time}}  ",
  "order_type_for_around": "{{order_type}} for around {{time}} ",
  "order_type_in_restaurant": "In restaurant",
  "order_type_not_available_dialog_description": "Looks like your order type is unavailable so we have chosen the next available order type for you",
  "order_type_with_price": "{{order_type}} • {{price}}",
  "order_with_app": "Order with app",
  "orders": "Orders",
  "paid": "Paid",
  "participating_restaurants": "Participating restaurants",
  "password": "Password {{required}} ",
  "password_rule_description": "Password needs to be at least 7 characters long and include at least 1 number",
  "password_updated": "Password updated",
  "passwords_dont_match": "Passwords don't match",
  "pay": "Pay",
  "pay_with": "Pay with {{payment_method}}",
  "paymaya_description": "We’ll ask you to log-in with PayMaya when placing an order",
  "payment_already_added_message": "You have the same payment method in your account. New one won't be added.",
  "payment_already_added_title": "Same payment method already exists",
  "payment_card_authorization_disclaimer": "\"\"",
  "payment_method_declined_dialog_message": "Double-check and try again or select a different payment method",
  "payment_method_declined_dialog_title": "Payment method declined",
  "payment_method_expired_dialog_message": "Please change your payment method or add a new one",
  "payment_method_expired_dialog_title": "Payment method expired",
  "payment_method_not_accepted_for_order_type": "{{payment_method}} not accepted for {{order_type}}",
  "payment_method_not_available_error_message": "{{venue_name}}  doesn't accept {{payment_method}}. Please change your payment method or add a new one.",
  "payment_method_not_available_error_title": "{{payment_method}} not accepted here",
  "payment_methods": "Payment methods",
  "payment_successful_status_message": "Your payment was successful. Enjoy!",
  "payment_will_be_refunded": "Sorry, the restaurant cancelled your order. A refund is on its way.",
  "paypal_description": "We’ll ask you to log-in with PayPal when placing an order",
  "paystack_bank": "Paystack Bank",
  "paystack_bank_description": "We’ll ask you to log-in with Paystack Bank when placing an order",
  "paystack_transfer": "Paystack Transfer",
  "paystack_transfer_description": "We’ll ask you to log-in with Paystack Transfer when placing an order",
  "paystack_use": "Use Paystack",
  "paystack_ussd": "Paystack USSD",
  "paystack_ussd_description": "We’ll ask you to log-in with Paystack USSD when placing an order",
  "paystack_visa_qr": "Paystack Visa QR",
  "paystack_visa_qr_description": "We’ll ask you to log-in with Paystack Visa QR when placing an order",
  "people_often_also_order": "People often also order",
  "permission_overlay_condition": "Allow all the time",
  "permission_overlay_description": "To receive location based special deals, turn on {{allow_all_the_time}} precise location access in settings",
  "permission_overlay_dialog_description": "Turn on {{allow_all_the_time}} precise location access in settings",
  "permission_overlay_heading": "Get the most from special deals",
  "permission_overlay_privacy": "We'll use your data to tailor special deals and promotions just for you. Learn more about our {{privacy_policy}}.",
  "permissions_phone_message": "To place a call, please turn on Phone permissions in Settings",
  "permissions_phone_title": "Turn on phone permissions to call",
  "phone": "Phone",
  "phone_changed": "Phone number changed",
  "phone_number": "Phone number",
  "phone_number_error": "Add phone number",
  "phone_number_info_message": "Please add your phone number so the restaurant can inform you about your order if needed",
  "pick_up_at": "for {{pickup_time}}",
  "pickup_in_restaurant": "Pick up in restaurant",
  "pickup_items_and_pay": "Pick your items and pay",
  "place_order": "Place order",
  "place_your_order": "Place your order",
  "please_enter_code": "Please enter the code we sent to {{email}}",
  "point": "point",
  "points_away": "You are {{number}} {{points}} away",
  "points_away_desc": "You’re {{points_away}} points away from earning your next {{reward_currency}} reward!",
  "points_credit_balance": "{{total_points}}  | {{credit_balance}}",
  "points_earned": "{{points}} earned ",
  "points_plural": "points",
  "points_spent": "{{points}} spent",
  "points_used": "{{number}} used",
  "points_you_will_earn": "{{points}} you'll earn",
  "postal_code_placeholder": "Postcode",
  "precise_location": "Precise Location",
  "preparing_order": "Preparing order",
  "price_free": "Free",
  "price_high_to_low": "Price: high to low",
  "price_low_to_high": "Price: low to high",
  "price_with_points": "{{price}} with {{number}}  {{points}} ",
  "prices_has_changed_dialog_description": "Looks like some prices have changed since your last order",
  "privacy_policy": "Privacy policy",
  "proceed": "Proceed",
  "proceed_terms_and_privacy_acceptance": "By proceeding, you accept our {{terms_of_service}}  and confirm that you have read our {{privacy_policy}}.",
  "product_discount_value_off": "- {{discount_value}}",
  "product_percentage_value": "{{percentage_value}}%",
  "profile": "Profile",
  "promo_code": "Promo code",
  "promotion": "Promotion",
  "promotion_added_dialog_message": "Enjoy your promo",
  "promotion_not_available": "You got promotion but it’s not available here",
  "promotion_not_available_order_types": "This promotion is only available for {{order_types}}",
  "promotion_not_available_ordering_flow": "This promotion is only available from the restaurant menu",
  "promotion_not_available_restaurant": "This promotion is only available in participating restaurants",
  "promotion_will_disappear_description": "Promotion will disappear when time runs out, or if you close this screen",
  "promotions": "Promotions",
  "province_placeholder": "Province",
  "pull_into_curbside_spot": "Pull into a Curbside parking spot when you arrive",
  "pull_into_parking_spot": "Pull into a Curbside parking spot",
  "quantity": "Quantity: {{quantity}}",
  "ready_to_use": "Ready to use",
  "ready_to_use_desc": "\"Ready to use\" indicates that your cart has all the items needed to apply the offer",
  "ready_to_use_tag": "Ready to use",
  "receipt": "Receipt",
  "receipt_with_number": "{{receipt}} #{{receipt_number}}",
  "receipts": "Receipts",
  "recently_added": "Recently added",
  "red_compra": "Red Compra",
  "red_compra_description": "We’ll ask you to log-in with Red Compra when placing an order",
  "red_compra_title": "Use Red Compra",
  "referral": "Referral",
  "referral_account_created": "Your referral offer was added to your account. Now you are part of the loyalty program. Enjoy all benefits.",
  "referral_code": "Referral code",
  "referral_code_max_error": "We are sorry. This code has been used the maximum number of times.",
  "referral_notif_offer_heading": "You got a new offer!",
  "referral_notif_paragraph": "{{user_name}} used your referral code and successfully placed their first order",
  "referral_notif_points_heading": "You got {{number}} {{points}}!",
  "refferal_replacing_dialogue_paragraph": "Sorry, you can only have one offer or reward with your order",
  "refferal_replacing_offer_dialogue_heading": "Your offer has been replaced with your referral offer",
  "refferal_replacing_reward_dialogue_heading": "Your reward has been replaced with your referral offer",
  "refine_location": "Refine location",
  "refund_on_its_way": "A refund is on its way",
  "refunded": "REFUNDED",
  "refunded_status_message": "The refunded amount will show on your payment method",
  "register_to_use": "Register to use",
  "relevance": "Relevance",
  "remaining": "{{time_out}} Remaining",
  "remove": "Remove",
  "remove_address": "Remove address",
  "remove_address_dialog_title": "Remove address?",
  "remove_discount": "Remove discount?",
  "remove_offer": "Remove offer?",
  "remove_promo_offer_desc": "Your offer is saved. Find it under offers section to use it later",
  "remove_promo_offer_title": "Do you want to remove the offer?",
  "remove_promocode_desc": "You can use the promo code later",
  "remove_promocode_title": "Do you want to remove the promo code?",
  "remove_reward": "Remove reward?",
  "reorder": "Reorder",
  "reorder_cta": "Order again",
  "reordering_failed_dialog_description": "Something went wrong. Please start a new order in the app.",
  "reordering_failed_dialog_title": "Oops!",
  "repeat_new_password": "Repeat new password {{required}}",
  "required": "required",
  "reset": "Reset",
  "restaurant_info_button": "Order now",
  "restaurants_closed_message": "All restaurants are currently closed. Please try again later.",
  "review_promotion_details_info": "Please review the promotion details to ensure the promotion is applied correctly",
  "reward": "Reward",
  "reward_already_added_dialog_title": "You already have a reward",
  "reward_condition_instruction": "Meet conditions to unlock the reward",
  "reward_disclaimer_text": "*Only in participating restaurants.",
  "reward_locked_earn_points": "It's locked. You need {{number}} {{points}} to get it.",
  "reward_will_disappear_description": "Reward will disappear when time runs out, or if you close this screen",
  "rewardoffer_active_modal_description": "Discount cards cannot be added while a discount card is active. Remove to add a discount card.",
  "rewardoffer_active_modal_title": "Rewards & Offers are active",
  "rewards": "Rewards",
  "rewards_and_offers": "Rewards & Offers",
  "rewards_bottom_tab": "Rewards",
  "rewards_home_heading": "Rewards",
  "rewards_terms": "Rewards terms",
  "room": "Room",
  "saturday": "Saturday",
  "save": "Save",
  "scan_barcode_on_kiosk": "Scan this barcode on kiosk",
  "scan_barcode_on_kiosk_or_cash_register": "Scan barcode on kiosk or cash register",
  "scan_code_kiosk": "Scan this code at the kiosk. Or, you can enter the card number manually.",
  "scan_instructions": "Scan instructions",
  "scan_receipt_access_camera": "{{app_name}}  Would Like to Access the Camera",
  "scan_receipt_access_camera_desc": "Enable camera access to scan a barcode to collect points or add a credit card for payment",
  "scan_receipt_barcode": "Scan receipt barcode",
  "scan_receipt_barcode_desc": "Scan the barcode on a receipt or enter the receipt code manually",
  "scan_to_collect_points": "Scan to collect {{points}}",
  "search_this_area": "Search this area",
  "seat": "Seat",
  "see_order_real_time": "See where your order is in real-time",
  "see_you_soon": "See you soon!",
  "select_all": "Select all",
  "select_at_least_rule": "Select at least {{rule_number}} ",
  "select_country": "Select country",
  "select_discount": "Select discount",
  "select_language": "Select language",
  "select_min_max_rule": "Select {{min_rule_number}}  to {{max_rule_number}}",
  "select_offer_or_reward": "Select offer or reward",
  "select_order": "Select order",
  "select_restaurant": "Select restaurant",
  "select_rule": "Select {{rule_number}} ",
  "select_table_footer_message": "Can't find your order? Please consult a waiter.",
  "select_up_to_rule": "Select up to {{rule_number}} ",
  "select_your_location": "Select your location",
  "send": "Send",
  "send_feedback": "Send feedback",
  "service_charge": "Service Charge",
  "settings": "Settings",
  "settle_bill": "Settle bill",
  "settle_bill_order_type_description": "Pay for what you ordered",
  "sf_onboarding_guide": "Select an order type to filter restaurants",
  "share": "Share {{brand_name}}",
  "share_app_message": "Download the app:",
  "share_app_url": "\"\"",
  "share_code_offer_heading": "Invite a friend, get an offer",
  "share_code_offer_paragraph": "Share this code with friends and get an offer when they use it on their first order.",
  "share_code_points_heading": "Invite a friend, get {{points}}",
  "share_code_points_paragraph": "Share this code with friends and get {{number}} {{points}} when they use it on their first order.",
  "share_earn": "Share and earn!",
  "share_earn_offer_paragraph": "Share this code with friends and get an offer when they use it on their first order",
  "share_earn_referral_paragraph": "Share this code with friends and get {{number}} {{points}} when they use it on their first order.",
  "share_link": "Share",
  "share_message": "Hey! Get promotion at {{brand_name}}. Use my referral code {{code}} when placing an order. {{link}}",
  "share_referral_code": "Share referral code",
  "share_your_ideas": "We appreciate your feedback. Describe an issue or share your ideas.",
  "show_all": "Show all",
  "show_all_offers": "Show all offers",
  "show_at_cash_register": "Show at cash register to pay",
  "show_at_cash_register_for_discount": "Show at cash register to get a discount",
  "show_at_cash_register_for_offer": "Show at cash register to get the offer",
  "show_at_cash_register_for_reward": "Show at the cash register to get a reward",
  "show_at_regsiter": "Show at cash register to pay",
  "show_barcode_at_cash_register": "Show this barcode at cash register",
  "show_barcode_at_cash_register_or_use_it_manually": "Show this barcode at cash register or use it manually",
  "show_code_to_cashier": "Show this code to cashier",
  "show_number": "Show {{number}} ",
  "show_participating_restaurants": "Show participating restaurants",
  "show_password": "Show password",
  "show_qrcode_cash_register": "Show the QR code at the cash register",
  "show_qrcode_cash_registered": "Show this QR code at the cash register",
  "show_to_cashier": "Show to cashier",
  "sign_in": "Sign in",
  "sign_out": "Sign out",
  "skip_create_account": "Skip and Create account",
  "smart_orders": "Smart orders",
  "smart_orders_cant_be_used": "Smart orders are not meant to be used if you are already here. You can still place your order as usual.",
  "smart_orders_description": "We’ll track your location in the background to start preparing your order when you’re nearby, so it’ll be ready exactly when you arrive",
  "smart_orders_need_location": "We need your location to be able to start preparing your order when you’re nearby",
  "smart_orders_need_location_turn_on": "Smart orders needs your location to detect when you are nearby. Turn on location in settings.",
  "smart_orders_need_precise_location": "Smart orders needs your {{precise_location}} access to detect when you are nearby.\u2028Turn on location in settings.",
  "snack_bar_delivery_promise_drivers_unavailable": "We don't have any drivers available right now. Please try again later.",
  "snack_mobile_ordering_not_available": "Mobile ordering is not available at the moment. You can still call the restaurant or go directly to place the order.",
  "sort_and_filter": "Sort and filter",
  "sort_by": "Sort by",
  "special_instructions": "Special instructions",
  "stop_tracking": "Stop Tracking",
  "store_temporarily_unavailable_for_orders": "Store is temporarily unavailable for digital orders",
  "store_temporarily_unavailable_for_orders_description": "The store delivering to your address is temporarily unavailable. We are working hard to bring it back as soon as possible.",
  "street": "Street ({{required}})",
  "subsidy": "Subsidy",
  "subtotal": "Subtotal",
  "sunday": "Sunday",
  "swiss_lunch_check": "Swiss Lunch-Check",
  "table": "Table",
  "takeout": "Takeout",
  "takeout_overlay_heading": "How will you pick up your order?",
  "tap_iam_here_button": "Tap the \"I'm here\" button",
  "tap_on_my_way": "Tap on I’m on my way",
  "tap_on_my_way_reminder": "Remember to tap on “I’m on my way” when you start your journey to the restaurant",
  "tell_when_you_arrive": "Pull into a Curbside parking spot and tell us when you arrive by tapping I'm here below",
  "temp_offline_snack": "Temporarily unavailable for digital orders. We are working hard to bring it back as soon as possible.",
  "temporarily_unavailable": "Temporarily unavailable for digital orders",
  "temporarily_unavailable_alert_order_message": "Temporarily orders cannot be placed at this store. We are working hard to bring it back as soon as possible.",
  "terms_apply": "Terms apply",
  "terms_of_service": "Terms of service",
  "terms_of_service_and_privacy_policy": "I agree to the {{terms_of_service}}  and confirm that I have read the {{privacy_policy}}.",
  "terms_update_paragraph": "We've updated our Terms of Service and Privacy Policy. Please take a moment to review the changes to the Terms of Service linked below and let us know that you agree to them. You must agree to the updated Terms of Service in order to continue using our app.",
  "terms_update_title": "Updates to our Terms of Service and Privacy Policy",
  "test_key_1": "Test",
  "thanks_for_feedback": "Thanks for your feedback ❤️",
  "this_will_start_new_order": "This will start a new order",
  "thursday": "Thursday",
  "time_in_hours": "{{hours}} h",
  "time_in_minutes": "{{minutes}} min",
  "time_in_seconds": "{{seconds}} seconds",
  "time_left_to_cancel": "{{time}} left to cancel",
  "time_to_collect": "Time to collect it. Enjoy!",
  "tip": "Tip",
  "tip_with_percentage": "Tip {{value}}%",
  "today_with_working_hours": "Today {{working_hours}}",
  "too_late_to_order": "Sorry, too late to order now.",
  "total": "Total",
  "track_order": "Track order",
  "transbank_duplicate_card_error": "There is already a card registered. If you want to replace it, please delete the existing one first.",
  "translate_menu": "Translate menu",
  "try_again": "Try Again",
  "tuesday": "Tuesday",
  "turn_on_location": "Turn on location",
  "turn_on_location_message": "We use your location to find you and to show nearby restaurants. Turn on location in settings.",
  "turn_on_notifications": "Turn on notifications",
  "turn_on_notifications_message": "Notifications let you know when your order is ready. Otherwise, you might miss it. Turn on notifications in settings.",
  "turn_on_smart_orders": "Turn on Smart orders",
  "unavailable_for_selected_time": "Item not available at selected time",
  "unlimited": "Unlimited",
  "unlocked": "Unlocked",
  "update": "Update",
  "update_loyalty_balance_info": "{{loyalty_points_name}} will be added to your loyalty balance 12 hours after the cash payment is completed",
  "update_loyalty_balance_info_receipt": "If you earned any {{points}} they will show up here and will be added to your balance 12 hours after the cash payment is completed",
  "update_required_description_message": "The app got even better! To continue ordering delicious food, install the latest version.",
  "update_required_title_message": "Oops, update needed",
  "use": "Use",
  "use_at_cash_register": "Use at cash register",
  "use_coupon_dialog_title": "Use coupon?",
  "use_credit_active": "Use credits is active ({{credit_amount}})",
  "use_credits": "Use credits",
  "use_credits_amountused_totalbalance": "Use credits ({{amount_used}} used of {{credit_balance}})",
  "use_credits_at_cash_register": "Use credits at the cash register",
  "use_credits_at_kiosk": "Use credits at kiosk",
  "use_credits_balance": "Use credits ({{credit_balance}})",
  "use_current_location": "Use current location",
  "use_discount_dialog_title": "Use discount?",
  "use_discount_in_mobile_description": "Add to your app order",
  "use_discount_in_mobile_title": "Use in mobile app",
  "use_discount_on_kiosk_description": "Add to your kiosk order",
  "use_discount_on_kiosk_title": "Use on kiosk",
  "use_ideal": "Use iDEAL",
  "use_manually": "Use manually",
  "use_manually_description": "You’ll have 5 minutes to use it manually",
  "use_manually_description_custom": "You'll have {{time_out}} to use it manually",
  "use_manually_dialog_title": "Use manually?",
  "use_mercado_pago": "Use Mercado Pago",
  "use_offer_dialog_title": "Use offer?",
  "use_offer_manually_dialog_title": "Use offer manually?",
  "use_offer_reward_instructions_desc": "Select \"Use offer or reward\" at kiosk. Bring your phone facing the barcode scanner to collect points from your kiosk order.",
  "use_pay_pal": "Use PayPal",
  "use_paymaya": "Use PayMaya",
  "use_points_home": "Use",
  "use_points_to_get_rewards": "Use {{points}} to get rewards",
  "use_reward_dialog_message": "{{points}} will be reduced right away. You'll have 5 minutes to use it.",
  "use_reward_dialog_title": "Use reward?",
  "use_your_points": "Use your {{points}}",
  "used": "Used",
  "used_by": "Used by {{user_name}}",
  "validate_cvv": "Validate CVV",
  "vat": "VAT ({{vat_values}}%)",
  "vat_exemption": "VAT Exemption",
  "vehicle": "Vehicle",
  "vehicle_color": "Color",
  "vehicle_description": "We'll use your vehicle brand, model, color and plate number to quickly locate you on the parking lot and hand you your order",
  "vehicle_license_plate": "Last 3 digits of license plate",
  "verify_email": "Verify email address",
  "verify_email_description": "To verify the changes, please enter the code we sent to {{email}} .",
  "verify_phone": "Verify phone number",
  "verify_phone_description": "To verify the changes, please enter the code we send you via SMS.",
  "view_all": "View all",
  "view_order": "View order",
  "waiting_to_connect": "Waiting to connect...",
  "walking": "Walking",
  "we_cant_find_you": "We can't find you",
  "we_tracking_location": "We’re tracking your location to know when to start preparing your order.",
  "we_use_your_location": "We use your location to show nearby restaurants and let you order from them.",
  "we_will_send_you_instruction": "We’ll send you instructions to sign in or create your account",
  "wednesday": "Wednesday",
  "welcome": "Welcome!",
  "what_are_you_up_to": "What are you up to?",
  "what_is_the_code": "What's the code?",
  "what_name_phonenumber": "What's your name and phone number?",
  "where_are_you": "Where are you?",
  "will_come_by": "I’ll come by",
  "will_pay_with": "I will pay with",
  "write_feedback": "Please write feedback",
  "wrong_card_number_error": "Wrong card number",
  "wrong_cvv_error": "CVV not valid",
  "wrong_email": "Wrong email",
  "wrong_number": "Wrong number",
  "wrong_order": "Wrong order",
  "wrong_zip_code": "Wrong ZIP code",
  "you_already_here": "It looks like you’re already here",
  "you_have_credit_balance": "You have {{credit_balance}} available",
  "you_will_be_faster_here": "It looks like you’ll be here faster than we can prepare your order",
  "you_will_be_there": "You’ll be there in about {{time}}",
  "youll_pay": "You'll pay",
  "your_email": "What's your email?",
  "your_order": "Your order",
  "your_orders": "Your orders",
  "your_points_will_expire": "Your {{points}} will expire on {{date}}",
  "your_thoughts": "Let us know your thoughts...",
  "your_vehicle": "Your vehicle",
  "zip_code": "ZIP Code"
};

export default mobileStrings;