const webStrings: { [key: string]: any } = {
   dine_in: 'Dine-in Pickup',
   dine_in_combined: 'Dine-in',
   // takeout: 'Takeout',
   // select_location: 'Select location',
   // current_location: 'Current location',
   // restaurants: 'Locations',
   // currently_closed: 'Currently closed',
   // venue_closing: 'Closing soon. Sorry, it`s too late to order now.',
   // venue_closed: 'Closed right now.',
   // venue_now_closed: 'Venue is now closed',
   // order_in_advance: 'Order in advance',
   // cant_place_order: 'Can`t place order.',
   // closed: 'Closed',
   // sign_out: 'Sign out',
   // show_on_map: 'Show on map',
   // order: 'Order',
   // for: 'For',
   // not_available: 'Not available',
   // order_summary: 'Order summary',
   // cart_items_not_available: 'Some items are not available. They are removed from your order.',
   // cart_items_removed: 'All items will be removed from your cart',
   // subtotal: 'Subtotal',
   // vat: 'VAT',
   // total: 'Total',
   // checkout: 'Checkout',
   // cart_will_show_here: 'Your cart will show up here',
   // view_order: 'View order',
   // more: 'More',
   // cancel: 'Cancel',
   // change: 'Change',
   // remove: 'Remove',
   // reset: 'Reset',
   // delete: 'Delete',
   // delete_account_back_button: "Back to Account settings",
   // delete_account_body: "If you delete your account",
   // delete_account_bullet_1: "You will no longer be able to log in with your account",
   // delete_account_bullet_2: "You will no longer be able to see receipts of all of your past orders",
   // delete_account_bullet_3: "You will no longer be able to order delicious meals from our restaurants",
   // delete_account_bullet_4: "You will no longer be able to access our latest offers",
   // delete_account_bullet_loyalty: "You will lose your {{number}} {{points}} ",
   // delete_account_button: "Delete account",
   // delete_account_confirmation: "Your account has been deleted",
   // delete_account_dialog_body: "Your account will be permanently deleted",
   // delete_account_dialog_title: "Are you sure you want to delete your account?",
   // delete_account_loading_time: "This can take up to 1 minute to complete",
   // delete_account_loading_title: "Deleting data",
   // delete_account_note: "Note: It can take up to 6 months for your data to be completely removed from our systems. Please review our Privacy policy for further information.",
   // delete_account_title: "Delete account",
   // ok: 'OK',
   // quantity: 'Quantity',
   // instructions: 'Special instructions',
   // comment_description: 'For example: "No olives please."',
   // maximum_characters: 'Maximum {{number}} characters',
   // update: 'Update',
   // add: 'Add',
   // item_not_available: 'This item is not available',
   // checkout_page_title: 'Checkout',
   // first_name: 'First Name',
   // last_name: 'Last Name',
   // email: 'Email',
   // phone: 'Phone number',
   // country_code: 'Country code',
   // menu: 'Menu',
   // to_menu: 'Back to menu',
   // order_for: 'for',
   // asap: 'ASAP',
   // order_placed: 'Order placed!',
   // order_placed_for: 'Order placed for',
   // order_placed_for_asap: 'Order placed for around',
   // message_when_ready: 'You\'ll get an SMS when it\'s ready',
   // to_start: 'Back to start',
   // at: 'at',
   // home: 'Home',
   // home_logo: 'Jump to Home screen',
   // home_title: 'Hi,',
   // home_title_customer: 'Hi {{customer}},',
   // home_subtitle: 'Nice to see you!',
   // directory: 'Directory',
   // chage_order_type: 'Change to {{orderType}}?',
   // chage_type_remove: 'This will remove items from your cart.',
   // chage_type_warning: 'Some items are not available for {{orderType}}. \nThey will be removed from your order.',
   // remove_item_title: 'Remove item from cart?',
   // remove_item_text: 'Are you sure you want to remove this item from your cart?',
   // select_number: 'Select {{number}}',
   // select_up_to: 'Select up to {{number}}',
   // select_from_to: 'Select {{number1}} to {{number2}}',
   // select_at_least: 'Select at least {{number}}',
   // browse_menu: 'Order now',
   // order_desc: '{{orderType}} for {{pickupTime}}',
   // max_char: 'Max. {{number}} characters',
   // code: 'Code',
   // missing_first_name: 'Add first name',
   // missing_last_name: 'Add last name',
   // missing_email: 'Add email',
   // wrong_email: 'Enter your email in format yourname@example.com',
   // missing_phone: 'Add phone',
   // missing_cc: 'Add code',
   // wrong_phone: 'Wrong phone number',
   // wrong_cc: 'Wrong country code',
   // closing_time_title: 'It\'s closing time',
   // closing_time_message: 'Sorry, it\'s too late to order now',
   // time_unavailable_title: 'Pickup time changed',
   // time_unavailable_message: 'Your selected time is no longer available. We selected the first available time for you.',
   // unavailable_items_title: 'Some items are not available',
   // unavailable_items_message: 'They are removed from your order',
   // empty_cart_title: 'Can\'t place this order',
   // empty_cart_message: 'Double-check your cart and try again',
   // location_error_title: 'We can\'t find you',
   // location_error_message: 'Allow location permissions in your browser and try again',
   // select_payment_method_above: 'Please select payment method above',
   // pay_with: 'Pay with',
   // terms: 'Terms of Service',
   // privacy: 'Privacy Policy',
   // and: 'and',
   // no_results: 'No results',
   // get_new_code: 'Get new code',
   // abort: 'Abort',
   // sign_in: 'Sign in',
   // continue: 'Continue',
   // use_reward: 'Use reward',
   // add_reward: 'Add reward to your order',
   // use_coupon: 'Use coupon',
   // add_coupon: 'Add coupon to your order',
   // use_points: 'Use points to get rewards',
   // points: 'Points',
   // generic_error: 'We ran into a problem 🤕',
   // generic_message: 'There was an interruption and we couldn\'t do what you wanted us to do',
   // have_discount: 'You already have a discount',
   // discount_error_message: 'Sorry, you can add only 1 discount to your order',
   // loyalty_points: 'Hooray 🎉 , you\'ll get {{number}} {{points}}',
   // loyalty_max: 'Maximum of {{number}} {{points}} reached. You won\'t get full amount of {{points}}.',
   // register_or_log: '💁‍♂ Register or log in and get {{points}} with this order.',
   // register_or_log_unregistered: '💁‍♂ Register or log in and get points with this order.',
   // customize: 'Customize',
   // edit_customize: 'Edit customization',
   // how_it_works: 'How it works',
   // explanation: 'How it works expalanation',
   // reward_locked: 'Its locked. You need {{number}} points to get it.',
   // rewards: 'Rewards',
   // show_rewards: 'Your rewards will show up here. Sign in or create account to start earning rewards.',
   // okay: 'Okay',
   // cookie_title: 'This site uses cookies',
   // cookie_message: `We use cookies for Analytics, in order to enhance & improve your experience, as well as to track when you are logged-in. For more information read our <a href="{{privacyLink}}" target="_blank" rel="noopener" class="link">Privacy Policy</a>`,
   // status: 'Status',
   // change_payment_method: 'Please change your payment method or add a new one',
   // payment_method_expired: 'Payment method expired',
   // place_order: 'Place order',
   // payment: 'Payment',
   // personal_info: 'Personal info',
   // payment_method: 'Payment method',
   // phone_number: 'Phone number',
   // add_payment_method: 'Add payment method',
   // delete_payment_method: 'Delete this payment method?',
   // payment_methods_show_up_here: 'Payment methods will show up here. Go ahead and add one.',
   // payment_card_authorization_disclaimer: '',
   // expired: 'Expired',
   // add_zip_code: 'Add ZIP Code',
   // zip_code: 'Zip code',
   // add_country: 'Add country',
   // country: 'Country',
   // validate_cvv: 'Validate CVV',
   // not_valid_cvv: 'CVV is not valid',
   // add_cvv: 'Add CVV',
   // security_code: 'Security code',
   // not_valid_year: 'Year is not valid',
   // add_year: 'Add year',
   // not_valid_month: 'Month is not valid',
   // add_month: 'Add month',
   // add_date: 'Add date',
   // expiration_date: 'Expiration date',
   // wrong_card_number: 'Wrong card number',
   // not_valid_card_number: 'Credit card number entered is not valid',
   // missing_card_number: 'Add card number',
   // card_number: 'Card number',
   // select_payment_method: 'Select payment method',
   // please_continue_facebook: 'Please continue with Facebook to sign in',
   // account_created_facebook: 'You created your account with facebook',
   // account_already_exists: 'Account for {{email}} already exists. Please sign in.',
   // already_have_account: 'You already have an account',
   // request_new_code: 'Please request new code to sign in or create account. Code will be send to {{email}}',
   // code_wrong_or_expired: 'Your code is wrong or it has expired',
   // only_numbers: 'Only numbers allowed',
   // no_letters: 'No letters allowed',
   // are_you_sure: 'Are you sure?',
   // miss_you: 'We\'ll miss you',
   // settings_saved: 'Settings saved',
   // already_registered: 'Already registered?',
   // create_account: 'Create account',
   // continue_with_payment: 'Continue with payment',
   // whats_your_name: 'Finally, what\'s your name?',
   // check_your_email: 'Please check your inbox and enter the code we sent to  {{email}}',
   // whats_the_code: `What's the code?`,
   // send_you_instructions_checkout: 'We\'ll send you instructions to create account at {{email}}',
   // send_you_instructions: 'We\'ll send you instructions to sign in or create account',
   // whats_your_email: 'What\'s your email?',
   // continue_with_email: 'Continue with email',
   // payment_methods: 'Payment methods',
   // account_settings: 'Account settings',
   // sign_in_create_account: 'Sign in or Create account',
   // select_language: 'Select language:',
   // amount: 'Amount',
   // language: 'Language:',
   // enter_code: 'Enter code',
   // resend_code: 'Resend code',
   // confirm: 'Confirm',
   // send: 'Send',
   // delivery: 'Delivery',
   // where: 'Where',
   // deliver_to: 'Deliver to',
   // delivers_to: 'Delivers to',
   // details: 'Details',
   // open: 'open',
   // min: 'min',
   // previous_addresses: 'Previous addresses',
   // add_building_number: 'Add building number',
   // add_delivery_address: 'Add delivery address',
   // remove_address: 'Remove Address',
   // we_do_not_deliver: 'Oh snap! We don\'t deliver to this address yet with our delivery service, but please try one of our delivery partners, which you can find on our website.',
   // no_details: 'No details',
   // select_delivery_address: 'Select delivery address',
   // use_current_location: 'Use current location',
   // save: 'Save',
   // wrong_code: 'Wrong code',
   // instruction_for_courier: 'Instruction for courier',
   // apartment_floor: 'Apartment / Floor',
   // chose_another_one: 'Please choose another one.',
   // we_do_not_deliver_to_this_address: 'Oh snap! We don`t deliver to this address',
   // remove_items_from_cart: 'This will remove items from your cart',
   // change_details: 'Change details',
   // change_to_new_address: 'Change to new address?',
   // message_when_on_the_way: 'You\'ll get an SMS when it\'s on the way',
   // call: 'Call',
   // opens_at: 'Opens at',
   // delivery_closed: 'Delivery closed. Sorry, too late to order now.',
   // delivery_closed_title: 'Delivery closed',
   // delivery_closed_text: 'Sorry, too late to order now',
   // delivery_placed_for_asap: 'Delivery placed for around',
   // delivery_placed_for: 'Delivery placed for',
   // delivery_placed: 'Delivery placed!',
   // delivery_address: 'Delivery address',
   // delivery_fee: 'Delivery fee',
   // free_delivery: 'Free delivery',
   // we_need_your_email: 'We need your email to create your account',
   // email_in_use: 'Email is already in use',
   // email_taken: '{{email}} is already taken',
   // continue_with_facebook: 'Continue with Facebook',
   // make_combo: 'Make it a combo?',
   // no_menu_translation: 'Unfortunately there is no menu translation for selected language.',
   // high_contrast: 'High contrast',
   // people_also_added: 'People often also order',
   // for_around: 'for around',
   // around_minutes: 'around {{time}} min',
   // asap_around_minutes: 'ASAP (in around {{time}} min)',
   // allergens: 'Allergens:',
   // disclamier: 'Food type, calories and allergens vary based on modifications made to item.\n' +
   //    '2000 calories a day is used for general nutrition advice, but calorie needs vary.\n' +
   //    'Additional information available upon request.',
   // coupons: 'Coupons',
   // register_to_use: 'REGISTER TO USE',
   // coupon_empty_message: 'Your coupons will show up here. We\'ll inform you when new coupons are available.',
   // rewards_and_coupons: 'Rewards & Coupons',
   // kcal: 'kcal',
   // next: 'Next',
   // email_promotions: 'Email promotions',
   // get_notified: 'Get notified about special offers, rewards and promotions',
   // care_about_privacy: 'We deeply care about your privacy',
   // use_your_data: `We'll use your data to tailor offers, awards and promotions just for you. We do not sell your data.`,
   // like_to_receive: 'I\'d like to receive special deals and promotions by email. You can opt-out any time in account settings.',
   // check_email_spam: 'Didn\'t get email? Check your spam folder.',
   // more_info: 'More info',
   // imprint: 'Imprint',
   // terms_of_service: 'Terms of Service',
   // privacy_policy: 'Privacy Policy',
   // terms_privacy_text_first_part: 'I agree to the ',
   // terms_privacy_text_second_part: ' and ',
   // terms_privacy_text_third_part: ' confirm i have read the ',
   // minimal_order_amount_text: 'The minimum order size is {{minimalAmount}}. You can still place the order, but unfortunately we have to charge you the difference.',
   // orders_below_fee: 'Fee for orders below {{minimalAmount}}',
   // discounts: 'Discounts',
   // promotions: 'Promotions',
   // add_promotion_order: 'Add promotion to your order',
   // expires: 'Expires',
   // enter_promo_code: 'Enter promo code',
   // got_promotion_discount: 'Hooray! 🎉 You got a promotion discount.',
   // promotions_show_here_registered: 'Your promotions will show up here. To get a promotion enter a promo code.',
   // promotions_show_here_unregistered: 'Your promotions will show up here. Sign in or create account to enable promotions and promo codes.',
   // promo_code: 'Promo Code',
   // only_numbers_and_letters: 'Only numbers and letters are allowed',
   // code_expired: 'Code expired',
   // code_already_used: 'Code already used',
   // card_expired: 'Card expired',
   // discount: 'Discount',
   // you_have_points: 'You have {{loyaltyPoints}} points',
   // orders: 'Orders',
   // orders_show_up_here: 'Your orders will show up here. Go ahead and order something delicious.',
   // back_to_orders: 'Back to orders',
   // refunded: 'Refunded',
   // around: 'around',
   // tip: 'Tip',
   // id: 'ID',
   // news: 'News',
   // view_all: 'View all',
   // coupons_in_article: 'Coupons in this article',
   // go_menu_coupon: 'Go to menu to use this coupon',
   // add_coupon_order: 'You can add this coupon to your order from the menu',
   // use_promotion: 'Use promotion',
   // starts: 'Starts',
   // no_expiry_date: 'No expiry date',
   // english: 'English',
   // german: 'Deutch',
   // icelandic: 'Icelandic',
   // french: 'French',
   // spanish: 'Spanish',
   // delivery_venue_closed: 'The location delivering to your address is currently closed. Please try again later.',
   // sign_in_with_apple: 'Sign in with Apple',
   // account_created_apple: 'You already created account with your Apple ID',
   // please_continue_apple: 'Please continue with your Apple ID to sign in',
   // apple_id_error_title: 'You already used your Apple ID',
   // apple_id_error_text: 'Please remove this application from your Apple ID Password and Security settings and try again.',
   // use: 'Use',
   // cash: 'Cash',
   // cash_amount_text: 'Please input the amount of cash you have so the courier can prepare change for you',
   // use_paypal: 'Use PayPal',
   // use_cash: 'Use Cash',
   // cash_order_text: 'The order will be placed when it\'s payed at a cash register',
   // cash_status_text: 'Show at cash register to pay',
   // cash_order_dinein_takeout_placed: 'Head to a cashier and pay your order.',
   // use_mercadopago: 'Use Mercado Pago',
   // pay_with_cash: 'Pay with cash',
   // pay_with_paypal: 'Pay with PayPal',
   // pay_with_mercadopago: 'Pay with Mercado Pago',
   // pay_with_ideal: 'Pay with iDEAL',
   // ask_to_login_paypal: `We'll ask you to log-in with PayPal when placing an order`,
   // ask_to_login_mercadopago: `We'll ask you to log-in with Mercado Pago when placing an order`,
   // ask_to_login_ideal: `We'll ask you to log-in with iDEAL when placing an order`,
   // payment_not_accepted_title: '{{method}} not accepted here',
   // payment_not_accepted_text: '{{venue}} doesn\'t accept {{method}}. Please change your payment method or add a new one.',
   // use_applepay: 'Use Apple Pay',
   // pay_with_applepay: 'Pay with Apple Pay',
   // ask_to_login_applepay: `We'll ask you to log-in with ApplePay when placing an order`,
   // applepay_not_supported: 'ApplePay is not supported in your browser. Please choose another payment method or use the Safari browser.',
   // applepay_merchant_validation_error : 'ApplePay validation failed. Please choose another payment method or contact support.',
   // applepay_general_error : 'ApplePay was not able to complete your order. Please choose another payment method or contact support.',
   // opening_hours: 'Opening Hours',
   // open_24_hours: 'Open 24h',
   // monday: 'Monday',
   // tuesday: 'Tuesday',
   // wednesday: 'Wednesday',
   // thursday: 'Thursday',
   // friday: 'Friday',
   // saturday: 'Saturday',
   // sunday: 'Sunday',
   // card_expired_text: 'The credit card expiry date you entered is expired. Please insert the correct expiry date and try again.',
   // wrong_card_number_text: 'You have inserted the wrong card number. Please insert the correct card number and try again.',
   // temporarily_offline: 'Temporarily unavailable for digital orders',
   // temporarily_offline_working_hard: 'Temporarily unavailable for digital orders. We are working hard to bring it back as soon as possible.',
   // cant_order_working_hard: 'Temporarily orders cannot be placed at this store. We are working hard to bring it back as soon as possible.',
   // send_feedback: 'Send feedback',
   // send_feedback_info: 'We appreciate your feedback. Describe an issue or share your ideas.',
   // send_feedback_placeholder: 'Let us know your thoughts...',
   // thank_you_feedback: 'Thanks for your feedback',
   // thank_you_feedback_info: 'Your voice is important to us in creating a better experience',
   // already_have_your_feedback: 'You already left feedback. We`re looking forward to your next order!',
   // send_feedback_min_length_validation_text: 'Minimum 50 characters',
   // send_feedback_max_length_validation_text: 'Maximum 1000 characters',
   // feedback_title: 'Feedback - Send us a message',
   // error_title: 'Error - Page not found',
   // orders_title: 'Orders - Your orders',
   // single_order_title: 'Order details',
   // checkout_title: 'Place order',
   // status_title: 'Order status',
   // account_title: 'User account - Account settings',
   // directory_title: 'Choose venue',
   // payment_methods_title: 'Payment methods - Manage your payments',
   // venue_title: 'Add items to the cart',
   // decrease_quantity_by_1: 'Decrease quantity by 1',
   // increase_quantity_by_1: 'Increase quantity by 1',
   // close: 'Close',
   // back: 'Back',
   // clear: 'Clear',
   // clear_search_field: 'Clear search field',
   // remove_item: 'Remove item',
   // clear_apartment_number: 'Clear apartment number',
   // previous_suggested_item: 'Previous suggested item',
   // next_suggested_item: 'Next suggested item',
   // click_for_previous_news: 'Click to go to previous News',
   // click_for_more_news: 'Click for more News',
   // search: 'Search',
   // jump_to: 'Jump to',
   // info: 'Info',
   // categories: 'menu categories',
   // select: 'Select',
   // article_about: 'Article about',
   // user_menu: 'User menu dropdown',
   // previous_news: 'Show previous News',
   // more_news: 'Show more News',
   // select_country: 'Select Country Dropdown',
   // vegan: 'Vegan',
   // vegetarian: 'Vegeterian',
   // list_locations: 'List of locations',
   // number_of_items: 'Number of items',
   // edit_delivery_address: 'Edit delivery address',
   // find_location: 'Find my location',
   // error_page_title: 'Page not found',
   // error_page_subtitle: 'We can\'t find what you\'re looking for',
   // error_page_button_text: 'Back to home',
   // sitemap_heading: 'Welcome to {{brandName}} sitemap page',
   // sitemap_title: 'Sitemap page',
   // general_pages: 'General pages',
   // terms_and_privacy_validation: 'To create an account you have to agree to the Terms of Service and Privacy Policy',
   // zoom_in: 'Zoom in',
   // zoom_out: 'Zoom out',
   // order_location: 'Order location',
   // order_time: 'Order time',
   // order_type: 'Order type',
   // user_logged_in: 'You are logged in',
   // user_logged_out: 'You are logged out',
   // payment_method_changed: 'Payment method changed',
   // number_of_payment_methods: 'Number of payment methods',
   // dine_in_FS: 'Table Service',
   // number: 'number',
   // clear_table_number: 'Clear table number',
   // table: 'Table',
   // for_table: 'for',
   // wrong_number: 'Wrong number',
   // choose_combo: 'Choose combo',
   // remove_discount_title: 'Remove discount?',
   // remove_discount_text: 'Are you sure you want to remove this discount?',
   // order_on_the_way: 'Your order is on the way. Enjoy!',
   // we_would_like_to_know_you_better: 'We\'d like to get to know you better',
   // add_birthday: 'Add birthday',
   // birthday_date: 'Birthday date (can be set only once)',
   // cart: 'cart',
   // street_name: 'Street name',
   // street_name_required: 'Street (required)',
   // clear_street_name: 'Clear street name',
   // building_name_number: 'Building Name/Number',
   // clear_building_name_number: 'Clear building name/number',
   // street_name_is_required: 'Street name is required',
   // remove_this_address: 'Remove this address?',
   // select_on_map: 'Select on map',
   // select_your_location: 'Select your location',
   // use_your_current_location: 'Use your current location',
   // adjust_pin: 'Adjust Pin',
   // add_address: 'Add New Address',
   // edit_address: 'Edit Address',
   // free: 'Free',
   // cancel_order: 'Cancel order',
   // cancel_order_title: 'Cancel order?',
   // go_back: 'Go back',
   // minutes: 'minutes',
   // seconds: 'seconds',
   // second: 'second',
   // left_to_cancel: 'left to cancel',
   // order_processing: 'Processing order',
   // canceled: 'Canceled',
   // order_cancel_time_expired: 'Time for order cancellation expired',
   // order_canceled: 'Order canceled',
   // refund_on_its_way: 'A refund is on it\'s way',
   // to_late_to_cancel: 'Sorry, it\'s to late to cancel your order',
   // call_for_assistance: 'For any additional assistance, please call the restaurant.',
   // delivery_tracking: 'Delivery Tracking',
   // processing: 'Processing',
   // preparing: 'Preparing',
   // delivering: 'Delivering',
   // track_delivery: 'Track delivery',
   // foodspot: 'Foodspot',
   // introducting_foodspot: 'Introducting Foodspot',
   // foodspot_intro: 'Foodspot is a convenient way of ordering onsite food. Offer companies and communities a platform to allow employees or group of people to order delivery to a station',
   // find_out_more: 'Find out more',
   // get_code_from_organization: 'Get the code from your organization',
   // previously_used: 'Previously used',
   // register_to_view: 'Register to view',
   // wrong_code_try_again: 'Wrong code. Please try again.',
   // to: 'To',
   // on_order: 'on order',
   // foodspot_is_closed_for_ordering: 'Foodspot is closed for ordering',
   // orders_are_accepted_until: 'Orders are accepted until',
   // order_time_is_not_available: 'Order time isn`t available',
   // selected_time_not_available: 'Your selected time isn`t available. Foodspot is closed for ordering.',
   // order_time_changed: 'Order time changed',
   // selected_time_changed: 'Your selected time isn`t available. We changed it to the first available time.',
   // register: 'Register',
   // track_order: 'Track order',
   // good_morning: 'Good Morning',
   // good_afternoon: 'Good Afternoon',
   // good_evening: 'Good Evening',
   // offers: 'Offers',
   // use_offer: 'Use offer',
   // your_rewards: 'Your rewards',
   // opt_out: 'Opt out',
   // rewards_terms: 'Rewards terms',
   // faq: 'FAQ',
   // congratulations: 'Congratulations',
   // earn_points: 'Earn points',
   // join_now: 'Join now',
   // maximum_points_reached: 'You\'ve reached the maximum number of points. Now it\'s time to start using them so you can collect even more.',
   // join_start_earning: 'Join and start earning',
   // loyalty_program_title: 'Your Rewards',
   // offers_and_rewards: 'Offers & Rewards',
   // add_offer: 'Add offer to your order',
   // add_offer_or_reward: 'Add offer or reward to your order',
   // recently_added: 'Recently added',
   // expiry_date: 'Expiry date',
   // sort_and_filter: 'Sort and filter',
   // show_all: 'Show all',
   // show: 'Show',
   // sort_by: 'Sort by',
   // unlimited: 'Unlimited',
   // expires_in: 'Expires in {{days}} days',
   // expires_at: 'Expires in {{days}} days at {{time}}',
   // clear_all: 'Clear all',
   // no_offers_available: 'Your offers will show up here, once they are available',
   // no_rewards_available: 'Your rewards will show up here, once they are available',
   // city: "City",
   // region: "Region",
   // meet_conditions: "Meet conditions to unlock discount",
   // points_you_will_earn: "{{points}} you'll earn",
   // and_get_points: "and get {{points}} with this order",
   // add_table_number: "Add table number",
   // scan_to_collect_points: 'Scan to collect {{points}}',
   // collect_points_description: 'Put this code under the scanner of the kiosk or cash register. Or, you can enter the card number manually.',
   // show_kiosk_scan_instructions: 'Show kiosk scan instructions',
   // hide_kiosk_scan_instructions: 'Hide kiosk scan instructions',
   // scan_instructions_paragraph: 'Select "Collect {{points}}" on kiosk checkout. Turn your phone towards the barcode scanner to collect points from your kiosk order.',
   // collect_points_description_POS_only: 'Put this code under the cash register\'s scanner',
   // points_plural: 'Points',
   // earn_points_new: 'Earn {{points}}',
   // collect_points: 'Collect {{points}}',
   // offer_conditions_not_met: 'Offer condition isn`t met. You can go to Checkout, but the offer will be removed from your cart.',
   // offer_or_reward_error_message: 'Sorry, you can add only one offer or reward to your order',
   // offer_not_applied: 'Offer can\'t be applied',
   // have_offer: 'You already have an offer',
   // meet_conditions_offer: 'Meet conditions to unlock the offer',
   // offer_in_account_order_types: 'Offer is added to your account and can be used for supported order types',
   // offer_in_account_specific_store: 'Offer is added to your account and you can use it in participating restaurants',
   // offer_not_for_order_type: 'Offer can`t be used for {{orderType}}',
   // offer_not_for_specific_store: 'Offer can`t be used in {{restaurant}}',
   // remove_offer_text: 'Are you sure you want to remove this offer?',
   // remove_offer_title: 'Remove offer?',
   // removing_this_item_offer_info: 'Removing this item will reduce your cart total below the amount needed to unlock the offer',
   // reward_conditions_not_met: 'Reward condition isn`t met. You can go to Checkout, but the reward will be removed from your cart.',
   // reward_not_applied: 'Reward can\'t be applied',
   // have_reward: 'You already have a reward',
   // meet_conditions_reward: 'Meet conditions to unlock the reward',
   // remove_reward_text: 'Are you sure you want to remove this reward?',
   // remove_reward_title: 'Remove reward?',
   // removing_this_item_reward_info: 'Removing this item will reduce your cart total below the amount needed to unlock the reward',
   // already_have_reward_tooltip: 'You already have a reward in your cart',
   // scan_instructions_paragraph_new: 'Select "Collect {{points}}" during checkout on a kiosk. Scan the barcode at the kiosk to collect {{points}} from your kiosk order.',
   // dine_in_FS_description: 'Order is served in restaurant with assigned table number',
   // dine_in_description: 'Order is served in restaurant',
   // takeout_description: 'Order is packed for outside',
   // delivery_description: 'Order is delivered to you',
   // foodspot_description: 'Order is delivered to your Foodspot',
   // we_do_not_support_this_order_type: 'We do not support this order type',
   // minimum_short: 'Min.',
   // no_prev_address: 'Your addresses will show up here',
   // select_restaurant: 'Select restaurant',
   // location_found: 'Location found',
   // take_look_at_cart: 'Take a look at the cart',
   // prices_updated: 'Prices have been updated',
   // your_points_will_expire: 'Your {{points}} will expire on {{date}}',
   // first_order_condition: 'On 1st order',
   // invite_history: 'Invite history',
   // invite_history_empty: 'Your invite history will show up here when your friends use your referral code to place their first order',
   // referral: 'Referral',
   // referral_code: 'Referral code',
   // referral_code_error: 'You can only add this offer if you are a new user who has never ordered before',
   // referrals_heading: 'Invite a friend, get an offer',
   // referrals_paragraph: 'Share this code with friends and get an offer when they use it on their first order.',
   // referrals_points_heading: 'Invite a friend, get {{points}}',
   // referrals_points_paragraph: 'Share this code with friends and get {{number}} {{points}} when they use it on their first order.',
   // share_earn: 'Share and earn!',
   // share_with: 'Share with',
   // share_your_code: 'Share referral code',
   // already_have_referral_dialogue: 'Looks like you already have a referral offer! We\'ve added it for you.',
   // not_eligible_referral_dialogue_heading: 'You are not eligible for this referral',
   // not_eligible_referral_dialogue_paragraph: 'This referral can be only used with your first order',
   // referral_code_max_error: 'We are sorry. This code has been used the maximum number of times.',
   // referral_email_subject: 'Here is something nice for you',
   // refferal_replacing_dialogue_paragraph: 'Sorry, you can only have one offer or reward with your order',
   // refferal_replacing_offer_dialogue_heading: 'Your offer has been replaced with your referral offer',
   // refferal_replacing_reward_dialogue_heading: 'Your reward has been replaced with your referral offer',
   // used_by: 'Used by {{user_name}}',
   // go_to_offers: 'Go to Offers',
   // got_refrerral_dilogue_paragraph: 'Go to Offers to add it to your cart',
   // got_refrerral_dilogue_title: 'Woohoo! You got a referral offer!',
   // share_message: 'Hey! Get [promotion name] at {{brand_name}}. Use my referral code {{code}} when placing an order. {{link}}',
   // dialog_offer_not_available_news_heading: 'Available soon!',
   // dialog_offer_not_available_news_paragraph: 'This offer will become available on {{date}}',
   // add_reward_or_offer: 'Add reward or offer to your order',
   // rewards_and_offers: 'Rewards & Offers',
   // terms_update_title: 'Updates to our Terms of Service and Privacy Policy',
   // terms_update_paragraph: 'We\'ve updated our Terms of Service and Privacy Policy. Please take a moment to review the changes to the Terms of Service linked below and let us know that you agree to them. You must agree to the updated Terms of Service in order to continue using our app.',
   // registration_modal_title: 'Sign in or Create account to proceed',
   // registration_modal_separator: 'Or',
   // registration_modal_guest_button: 'Continue as Guest',
   // checkout_contact_information: 'Contact information',
   // checkout_contact_information_name: 'Your name',
   // checkout_payment_method_description: 'Select payment method to continue',
   // missing_name: 'Add name',
   // optout_dialog_title: 'To opt out you must delete your account',
   // optout_dialog_paragraph: 'If you decide to no longer be a part of loyalty program you must delete your account.',
   // proceed: 'Proceed',
   // postal_code_placeholder: 'Postal Code',
   // order_number_cash: 'Order placed! Head to a cashier and pay using your order number',
   // order_number_filled: 'Your order number',
   // order_number_empty: 'Your order number has not yet been assigned. We\'ll send you a SMS when it is available',
   // order_number_ond: 'Order placed! Your order number will appear on the restaurant\'s order screen when it\'s ready',
   // order_number_placeholder: '_ _ _',
   // update_loyalty_balance_info: '{{points}} will be added to your loyalty balance 12 hours after the cash payment is completed.',
   // smart_banner_title: 'Continue in mobile app?',
   // smart_banner_description: 'Enjoy exclusive offers and even better experience by using our native mobile app on your mobile device',
   // smart_banner_button_primary: 'Continue in mobile app?',
   // smart_banner_button_secondary: 'Not now',
   // update_loyalty_balance_info_order: 'If you earned any {{points}} they will show up here and will be added to your loyalty balance 12 hours after the cash payment is completed',
   // youll_pay: "You'll pay",
   // subsidy: "Subsidy",
   // foodspot_subsidy: "Foodspot Subsidy",
   // paid: "Paid",
   // foodspot_discount_description: "{{number}} % off your order",
   // foodspot_subsidy_amount: "Foodspot Subsidy ({{subsidy_amount}})",
   // edit_email: "Edit email address",
   // verify_email: "Verify email address",
   // verify_email_description: "To verify the changes, please enter the code we sent to {{email}}.",
   // request_new_code_2: "Please request a new code. Code will be send to {{email}}."
};

export default webStrings;